default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: curated_shop_development

test:
  <<: *default
  database: curated_shop_test

production:
  <<: *default
  url: <%= ENV['HANDLISTED_DATABASE_URL'] %>
