---
:daemon: false
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
production:
  :concurrency: 20
:queues:
  - [low_priority,  1]
  - [default,       2]
  - [high_priority, 4]
