---
:daemon: false
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :daemon: true
  :concurrency: 20
  :logfile: ./log/sidekiq.log
:queues:
  - default
  - [high_priority, 2]


