---
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
production:
  :daemon: true
  :logfile: ./log/sidekiq.log
  :concurrency: 20
:queues:
  - [low_priority,  1]
  - [default,       2]
  - [high_priority, 4]
