$ -> 
  ### @custom validation method (smartCaptcha) 
  ------------------------------------------------------------------ 
  ###

  $.validator.methods.smartCaptcha = (value, element, param) ->
    value == param

  $('.admin-form').validate
    errorClass: 'state-error'
    validClass: 'state-success'
    errorElement: 'em'
    rules:
      firstname: required: true
      lastname: required: true
      useremail:
        required: true
        email: true
      website:
        required: true
        url: true
      language: required: true
      upload1:
        required: true
        extension: 'jpg|png|gif|jpeg|doc|docx|pdf|xls|rar|zip'
      mobileos: required: true
      comment:
        required: true
        minlength: 30
      mobile_phone: require_from_group: [
        1
        '.phone-group'
      ]
      home_phone: require_from_group: [
        1
        '.phone-group'
      ]
      password:
        required: true
        minlength: 6
        maxlength: 16
      repeatPassword:
        required: true
        minlength: 6
        maxlength: 16
        equalTo: '#password'
      gender: required: true
      languages: required: true
      verification:
        required: true
        smartCaptcha: 19
      applicant_age:
        required: true
        min: 16
      licence_no: required: (element) ->
        $('#applicant_age').val() > 19
      child_name: required: '#parents:checked'
    messages:
      datepicker1: required: 'Select a Date'
      firstname: required: 'Enter first name'
      lastname: required: 'Enter last name'
      useremail:
        required: 'Enter email address'
        email: 'Enter a VALID email address'
      website:
        required: 'Enter your website URL'
        url: 'URL should start with - http://www'
      language: required: 'Choose a language'
      upload1:
        required: 'Please browse a file'
        extension: 'File format not supported'
      mobileos: required: 'Please select a mobile platform'
      comment:
        required: 'Oops you forgot to comment'
        minlength: 'Enter at least 30 characters or more'
      mobile_phone: require_from_group: 'Fill at least a mobile contact'
      home_phone: require_from_group: 'Fill at least a home contact'
      password: required: 'Please enter a password'
      repeatPassword:
        required: 'Please repeat the above password'
        equalTo: 'Password mismatch detected'
      gender: required: 'Please choose specie'
      languages: required: 'Select laguages spoken'
      verification:
        required: 'Please enter verification code'
        smartCaptcha: 'Oops - enter a correct verification code'
      applicant_age:
        required: 'Enter applicant age'
        min: 'Must be 16 years and above'
      licence_no: required: 'Enter licence number'
      child_name: required: 'Please enter your childs name'
    highlight: (element, errorClass, validClass) ->
      $(element).closest('.field').addClass(errorClass).removeClass validClass
      return
    unhighlight: (element, errorClass, validClass) ->
      $(element).closest('.field').removeClass(errorClass).addClass validClass
      return
    errorPlacement: (error, element) ->
      if element.is(':radio') or element.is(':checkbox')
        element.closest('.option-group').after error
      else
        error.insertAfter element.parent()
      return

  # ---
  # generated by js2coffee 2.1.0
